/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Avatar : AvatarBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	// Please inherit and implement "class Avatar : AvatarBase"
	public abstract class AvatarBase : Entity
	{
		public EntityBaseEntityCall_AvatarBase baseEntityCall = null;
		public EntityCellEntityCall_AvatarBase cellEntityCall = null;

		public Int32 diamond = 0;
		public virtual void onDiamondChanged(Int32 oldValue) {}
		public Int32 exp = 0;
		public virtual void onExpChanged(Int32 oldValue) {}
		public Int64 gold = 0;
		public virtual void onGoldChanged(Int64 oldValue) {}
		public Int32 locked = 0;
		public virtual void onLockedChanged(Int32 oldValue) {}
		public Int32 mapID = 0;
		public virtual void onMapIDChanged(Int32 oldValue) {}
		public string name = "";
		public virtual void onNameChanged(string oldValue) {}


		public AvatarBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AvatarBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AvatarBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 8:
						Int32 oldval_diamond = diamond;
						diamond = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onDiamondChanged(oldval_diamond);
						}
						else
						{
							if(inWorld)
								onDiamondChanged(oldval_diamond);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 6:
						Int32 oldval_exp = exp;
						exp = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onExpChanged(oldval_exp);
						}
						else
						{
							if(inWorld)
								onExpChanged(oldval_exp);
						}

						break;
					case 7:
						Int64 oldval_gold = gold;
						gold = stream.readInt64();

						if(prop.isBase())
						{
							if(inited)
								onGoldChanged(oldval_gold);
						}
						else
						{
							if(inWorld)
								onGoldChanged(oldval_gold);
						}

						break;
					case 3:
						Int32 oldval_locked = locked;
						locked = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onLockedChanged(oldval_locked);
						}
						else
						{
							if(inWorld)
								onLockedChanged(oldval_locked);
						}

						break;
					case 5:
						Int32 oldval_mapID = mapID;
						mapID = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMapIDChanged(oldval_mapID);
						}
						else
						{
							if(inWorld)
								onMapIDChanged(oldval_mapID);
						}

						break;
					case 4:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Int32 oldval_diamond = diamond;
			Property prop_diamond = pdatas[4];
			if(prop_diamond.isBase())
			{
				if(inited && !inWorld)
					onDiamondChanged(oldval_diamond);
			}
			else
			{
				if(inWorld)
				{
					if(prop_diamond.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDiamondChanged(oldval_diamond);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Int32 oldval_exp = exp;
			Property prop_exp = pdatas[5];
			if(prop_exp.isBase())
			{
				if(inited && !inWorld)
					onExpChanged(oldval_exp);
			}
			else
			{
				if(inWorld)
				{
					if(prop_exp.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onExpChanged(oldval_exp);
					}
				}
			}

			Int64 oldval_gold = gold;
			Property prop_gold = pdatas[6];
			if(prop_gold.isBase())
			{
				if(inited && !inWorld)
					onGoldChanged(oldval_gold);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gold.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGoldChanged(oldval_gold);
					}
				}
			}

			Int32 oldval_locked = locked;
			Property prop_locked = pdatas[7];
			if(prop_locked.isBase())
			{
				if(inited && !inWorld)
					onLockedChanged(oldval_locked);
			}
			else
			{
				if(inWorld)
				{
					if(prop_locked.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onLockedChanged(oldval_locked);
					}
				}
			}

			Int32 oldval_mapID = mapID;
			Property prop_mapID = pdatas[8];
			if(prop_mapID.isBase())
			{
				if(inited && !inWorld)
					onMapIDChanged(oldval_mapID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_mapID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMapIDChanged(oldval_mapID);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[9];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
}